name: client object storage nCloud

on:
  pull_request:
    types: [closed]
    branches:
    - '?*\-web\/master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: react-build 
      run: |
        path=$(echo ${GITHUB_BASE_REF%-web/master})
        cd ./webapps/$path
        yarn
        yarn build
    - name: react-build-dir
      run: echo "##[set-output name=dir]./webapps/$(echo $GITHUB_BASE_REF%-web/master})/build/"
      id: Dir
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'kr-standard'
        SOURCE_DIR: ${{ steps.Dir.outputs.dir }}
        AWS_S3_ENDPOINT:  https://kr.object.ncloudstorage.com
