name: server api test

on: 
  pull_request:
    branches:
      - '?*\-api\/master'

jobs:
  build:

    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, test
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.PRIVATEKEY }}
      run: |
        path=$(echo ${GITHUB_BASE_REF%-api/master})
        cd ./apis/$path
        if [ -e env.ssl ]; then
          echo -----BEGIN RSA PRIVATE KEY----- > private.pem
          echo $LARGE_SECRET_PASSPHRASE >> private.pem
          echo -----END RSA PRIVATE KEY----- >> private.pem
          openssl rsautl -decrypt -inkey private.pem -in env.ssl -out .env
        fi
        yarn
        yarn build
        cp .env ./build/
        yarn test
